name: Stale PR Report

on:
  schedule:
  - cron:  '25 22 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
    - name: Send Report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_EXTENDED }}
        SENDGRID_PASSWORD: ${{ secrets.SENDGRID_PASSWORD }}
        EMAIL_ADDRESS: community-experience@puppet.com
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake stale_pulls
        bundle exec rake codeowner_coverage

